### ISSUE TITLE
./biz_server cannot start

### ISSUE THREAD

**Issue by askucher** [nebula-chat/chatengine#16]
Everything compiled correctly. 

All these services started correctly
```
cd $GOPATH/src/github.comnebula-chat/chatengine/service/auth_session
./auth_session

cd $GOPATH/src/github.com/nebula-chat/chatengine/service/document
./document

cd $GOPATH/src/github.com/nebula-chat/chatengine/messenger/sync
./sync

cd $GOPATH/src/github.com/nebula-chat/chatengine/messenger/upload
./upload
```

Problem with

```sh
root@testchat:/var/workspace/src/github.com/nebula-chat/chatengine/messenger/biz_server# ./biz_server

```

Got
```
I0625 18:25:08.731736    8181 app_instance.go:60] instance initialize...
I0625 18:25:08.731997    8181 messenger.go:99] messengerServer - initialize...
I0625 18:25:08.732791    8181 messenger.go:106] messengerServer - load conf: &{1 127.0.0.1 0xc000118540 [{immaster root:@tcp(127.0.0.1:3306)/chatengine?charset=utf8mb4 5 2} {imslave root:@tcp(127.0.0.1:3306)/chatengine?charset=utf8mb4 5 2}] [{cache 127.0.0.1:6379 100 100 1000000000 1000000000 1000000000 10000000000 0 }] 0xc000096c40 0xc000096a80 0xc000096b40 0xc000096bc0}
E0625 18:25:13.738853    8181 rpc_client.go:78] context deadline exceeded
panic: context deadline exceeded

goroutine 1 [running]:
github.com/nebula-chat/chatengine/pkg/grpc_util.NewRPCClientByServiceDiscovery(0xc000096c40, 0x12e47e0, 0xc000155d10, 0xc0000b4ea0)
        /var/workspace/src/github.com/nebula-chat/chatengine/pkg/grpc_util/rpc_client.go:79 +0x904
github.com/nebula-chat/chatengine/service/document/client.InstallNbfsClient(0xc000096c40)
        /var/workspace/src/github.com/nebula-chat/chatengine/service/document/client/rpc_document_client.go:37 +0x2f
main.(*messengerServer).Initialize.func1()
        /var/workspace/src/github.com/nebula-chat/chatengine/messenger/biz_server/messenger.go:117 +0xef
github.com/nebula-chat/chatengine/messenger/biz_server/biz/core.InstallCoreModels(0x1, 0x157fce0, 0x1, 0xc000655e00, 0x2)
        /var/workspace/src/github.com/nebula-chat/chatengine/messenger/biz_server/biz/core/core.go:63 +0x248
main.(*messengerServer).Initialize(0xc000aec6e0, 0x15ab915900000000, 0x1)
        /var/workspace/src/github.com/nebula-chat/chatengine/messenger/biz_server/messenger.go:108 +0x1a7
github.com/nebula-chat/chatengine/pkg/util.DoMainAppInstance(0x18077c0, 0xc000aec6e0)
        /var/workspace/src/github.com/nebula-chat/chatengine/pkg/util/app_instance.go:61 +0x175
main.main()
        /var/workspace/src/github.com/nebula-chat/chatengine/messenger/biz_server/messenger.go:163 +0x95
root@indachat:/var/workspace/src/github.com/nebula-chat/chatengine/messenger/biz_server# 
```
from this issue, I have to launch the load balancer ...  https://github.com/liyue201/grpc-lb
did not find documentation for dev setup for load balance

Tthe starting process of `access/auth_key` , `access/session` has the same problem

frontend started normally

**Comment by wubenqi** [comment]
check document service started??

**Comment by askucher** [comment]
the problem is connected to exta sql scripts

**Comment by y396com** [comment]
> the problem is connected to exta sql scripts

Can you tell me  how to fix this problem?Thank you.
