### ISSUE TITLE
运行时间长了，session服务会崩溃

### ISSUE THREAD

**Issue by msj456** [nebula-chat/chatengine#20]
goroutine 282555 [sync.Cond.Wait, 10 minutes]:
sync.runtime_notifyListWait(0xc000da42d0, 0x7)
	/usr/lib/golang/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc000da42c0)
	/usr/lib/golang/src/sync/cond.go:56 +0x92
github.com/nebula-chat/chatengine/pkg/queue2.(*SyncQueue).Pop(0xc000f5f860, 0xc000cdf540, 0xc000cdf540)
	/root/src/github.com/nebula-chat/chatengine/pkg/queue2/sync_queue.go:51 +0x5b
github.com/nebula-chat/chatengine/access/session/server.(*authSessions).rpcRunLoop(0xc000455cc0)
	/root/src/github.com/nebula-chat/chatengine/access/session/server/auth_sessions.go:404 +0x48
created by github.com/nebula-chat/chatengine/access/session/server.(*authSessions).Start
	/root/src/github.com/nebula-chat/chatengine/access/session/server/auth_sessions.go:356 +0x6c

goroutine 156673 [select]:
github.com/nebula-chat/chatengine/access/session/server.(*authSessions).runLoop(0xc001da4320)
	/root/src/github.com/nebula-chat/chatengine/access/session/server/auth_sessions.go:373 +0x16f
created by github.com/nebula-chat/chatengine/access/session/server.(*authSessions).Start
	/root/src/github.com/nebula-chat/chatengine/access/session/server/auth_sessions.go:357 +0x8e

goroutine 284740 [select]:
github.com/nebula-chat/chatengine/access/session/server.(*authSessions).runLoop(0xc000454a00)
	/root/src/github.com/nebula-chat/chatengine/access/session/server/auth_sessions.go:373 +0x16f
created by github.com/nebula-chat/chatengine/access/session/server.(*authSessions).Start
	/root/src/github.com/nebula-chat/chatengine/access/session/server/auth_sessions.go:357 +0x8e

**Comment by wubenqi** [comment]
谢谢，我来找找原因

**Comment by msj456** [comment]
客气

**Comment by sg552** [comment]
原因找到了吗？
