### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by HentaiStorm** [nebula-chat/chatengine#47]
Not compiling, please help!

Traceback:
```
# github.com/nebula-chat/chatengine/mtproto
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xe44822, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc014000000, 0x4000000, 0x15c6938)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x159e940, 0x2000, 0x41c922, 0x7fbf1be36008)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x159e940, 0x1, 0xffffffff)
        /usr/local/go/src/runtime/mheap.go:1252 +0x42
runtime.(*mheap).allocSpanLocked(0x159e940, 0x1, 0x15c6948, 0xc000021320)
        /usr/local/go/src/runtime/mheap.go:1163 +0x291
runtime.(*mheap).alloc_m(0x159e940, 0x1, 0x7ffc0fa70012, 0x45892a)
        /usr/local/go/src/runtime/mheap.go:1015 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1086 +0x4c
runtime.systemstack(0x45a284)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0132d2478 sp=0xc0132d247                                                                                                 0 pc=0x45a380
runtime.(*mheap).alloc(0x159e940, 0x1, 0xc00d010012, 0xc0132d2628)
        /usr/local/go/src/runtime/mheap.go:1085 +0x8a fp=0xc0132d24c8 sp=0xc0132                                                                                                 d2478 pc=0x424f1a
runtime.(*mcentral).grow(0x159f160, 0x0)
        /usr/local/go/src/runtime/mcentral.go:255 +0x7b fp=0xc0132d2508 sp=0xc01                                                                                                 32d24c8 pc=0x416f7b
runtime.(*mcentral).cacheSpan(0x159f160, 0x203000)
        /usr/local/go/src/runtime/mcentral.go:106 +0x2fe fp=0xc0132d2568 sp=0xc0                                                                                                 132d2508 pc=0x416a9e
runtime.(*mcache).refill(0x7fbf1be29008, 0x12)
        /usr/local/go/src/runtime/mcache.go:138 +0x85 fp=0xc0132d2588 sp=0xc0132                                                                                                 d2568 pc=0x416545
runtime.(*mcache).nextFree(0x7fbf1be29008, 0xc0132d2512, 0x4435cc, 0x0, 0xe31ca0                                                                                                 )
        /usr/local/go/src/runtime/malloc.go:854 +0x87 fp=0xc0132d25c0 sp=0xc0132                                                                                                 d2588 pc=0x40b797
runtime.mallocgc(0x80, 0xe22d40, 0xfccc01, 0x0)
        /usr/local/go/src/runtime/malloc.go:1022 +0x793 fp=0xc0132d2660 sp=0xc01                                                                                                 32d25c0 pc=0x40c0d3
runtime.newobject(0xe22d40, 0x0)
        /usr/local/go/src/runtime/malloc.go:1151 +0x38 fp=0xc0132d2690 sp=0xc013                                                                                                 2d2660 pc=0x40c4c8
cmd/compile/internal/gc.(*Node).copy(...)
        /usr/local/go/src/cmd/compile/internal/gc/subr.go:397
cmd/compile/internal/gc.(*inlsubst).node(0xc0132d2f38, 0xc000b7f180, 0x321f00000                                                                                                 51a6)
        /usr/local/go/src/cmd/compile/internal/gc/inl.go:1255 +0x91b fp=0xc0132d                                                                                                 2898 sp=0xc0132d2690 pc=0xc4304b
cmd/compile/internal/gc.(*inlsubst).node(0xc0132d2f38, 0xc000b7f100, 0xc013fffb8                                                                                                 0)
        /usr/local/go/src/cmd/compile/internal/gc/inl.go:1263 +0x9f8 fp=0xc0132d                                                                                                 2aa0 sp=0xc0132d2898 pc=0xc43128
cmd/compile/internal/gc.(*inlsubst).list(0xc0132d2f38, 0xc0132d2e90, 0x1, 0x4, 0                                                                                                 xc0132d2da0)
        /usr/local/go/src/cmd/compile/internal/gc/inl.go:1182 +0xe0 fp=0xc0132d2                                                                                                 b28 sp=0xc0132d2aa0 pc=0xc42660
cmd/compile/internal/gc.mkinlcall(0xc00653e400, 0xc0072ba000, 0x50, 0xc013ffe900                                                                                                 )
        /usr/local/go/src/cmd/compile/internal/gc/inl.go:1074 +0x2d28 fp=0xc0132                                                                                                 d2fc0 sp=0xc0132d2b28 pc=0xc40548
cmd/compile/internal/gc.inlnode(0xc00653e400, 0x50, 0xc013ffe900)
        /usr/local/go/src/cmd/compile/internal/gc/inl.go:696 +0xafa fp=0xc0132d3                                                                                                 1c0 sp=0xc0132d2fc0 pc=0xc3cb0a
cmd/compile/internal/gc.inlnodelist(0xc006529b60, 0x50)
        /usr/local/go/src/cmd/compile/internal/gc/inl.go:528 +0x6e fp=0xc0132d32                                                                                                 00 sp=0xc0132d31c0 pc=0xc3bfbe
cmd/compile/internal/gc.inlnode(0xc00653c000, 0x50, 0xc0132d3430)
        /usr/local/go/src/cmd/compile/internal/gc/inl.go:623 +0x377 fp=0xc0132d3                                                                                                 400 sp=0xc0132d3200 pc=0xc3c387
cmd/compile/internal/gc.inlcalls(0xc00653c000)
        /usr/local/go/src/cmd/compile/internal/gc/inl.go:484 +0x77 fp=0xc0132d34                                                                                                 40 sp=0xc0132d3400 pc=0xc3b8d7
cmd/compile/internal/gc.Main.func6(0xc0013c4108, 0x1, 0xf, 0xc0130f5c00)
        /usr/local/go/src/cmd/compile/internal/gc/main.go:632 +0x3c fp=0xc0132d3                                                                                                 4d0 sp=0xc0132d3440 pc=0xd32ebc
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc0132d37a8, 0xc00653c000, 0x0                                                                                                 )
        /usr/local/go/src/cmd/compile/internal/gc/scc.go:118 +0x295 fp=0xc0132d3                                                                                                 550 sp=0xc0132d34d0 pc=0xc96335
cmd/compile/internal/gc.(*bottomUpVisitor).visit.func1(0xc00652ab00, 0xc0132d35d                                                                                                 0)
        /usr/local/go/src/cmd/compile/internal/gc/scc.go:81 +0xaf fp=0xc0132d35a                                                                                                 8 sp=0xc0132d3550 pc=0xd349ff
cmd/compile/internal/gc.inspect(0xc00652ab00, 0xc0132d3760)
        /usr/local/go/src/cmd/compile/internal/gc/syntax.go:912 +0xfc fp=0xc0132                                                                                                 d35c8 sp=0xc0132d35a8 pc=0xcf026c
cmd/compile/internal/gc.inspectList(0xc0065283a0, 0xc0132d3760)
        /usr/local/go/src/cmd/compile/internal/gc/syntax.go:925 +0x58 fp=0xc0132                                                                                                 d3600 sp=0xc0132d35c8 pc=0xcf02e8
cmd/compile/internal/gc.inspect(0xc00652ab80, 0xc0132d3760)
        /usr/local/go/src/cmd/compile/internal/gc/syntax.go:918 +0xac fp=0xc0132                                                                                                 d3620 sp=0xc0132d3600 pc=0xcf021c
cmd/compile/internal/gc.inspectList(0xc0065283c0, 0xc0132d3760)
        /usr/local/go/src/cmd/compile/internal/gc/syntax.go:925 +0x58 fp=0xc0132                                                                                                 d3658 sp=0xc0132d3620 pc=0xcf02e8
cmd/compile/internal/gc.inspect(0xc00652a780, 0xc0132d3760)
        /usr/local/go/src/cmd/compile/internal/gc/syntax.go:919 +0xc8 fp=0xc0132                                                                                                 d3678 sp=0xc0132d3658 pc=0xcf0238
cmd/compile/internal/gc.inspectList(0xc006528500, 0xc0132d3760)
        /usr/local/go/src/cmd/compile/internal/gc/syntax.go:925 +0x58 fp=0xc0132                                                                                                 d36b0 sp=0xc0132d3678 pc=0xcf02e8
cmd/compile/internal/gc.inspect(0xc00652a280, 0xc0132d3760)
        /usr/local/go/src/cmd/compile/internal/gc/syntax.go:918 +0xac fp=0xc0132                                                                                                 d36d0 sp=0xc0132d36b0 pc=0xcf021c
cmd/compile/internal/gc.inspectList(0xc006528520, 0xc0132d3760)
        /usr/local/go/src/cmd/compile/internal/gc/syntax.go:925 +0x58 fp=0xc0132                                                                                                 d3708 sp=0xc0132d36d0 pc=0xcf02e8
cmd/compile/internal/gc.(*bottomUpVisitor).visit(0xc0132d37a8, 0xc006516580, 0xb                                                                                                 fc3814800004106)
        /usr/local/go/src/cmd/compile/internal/gc/scc.go:76 +0x13d fp=0xc0132d37                                                                                                 88 sp=0xc0132d3708 pc=0xc961dd
cmd/compile/internal/gc.visitBottomUp(0xc00bc64000, 0x8552, 0x8c00, 0xe5bf88)
        /usr/local/go/src/cmd/compile/internal/gc/scc.go:58 +0x95 fp=0xc0132d37e                                                                                                 8 sp=0xc0132d3788 pc=0xc96075
cmd/compile/internal/gc.Main(0xe5be50)
        /usr/local/go/src/cmd/compile/internal/gc/main.go:623 +0x3a6f fp=0xc0132                                                                                                 d3ee8 sp=0xc0132d37e8 pc=0xc4995f
main.main()
        /usr/local/go/src/cmd/compile/main.go:51 +0xac fp=0xc0132d3f60 sp=0xc013                                                                                                 2d3ee8 pc=0xd7fddc
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0132d3fe0 sp=0xc0132d                                                                                                 3f60 pc=0x42f35e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0132d3fe8 sp=0xc01                                                                                                 32d3fe0 pc=0x45c2d1
```

Go: 1.13 and 1.14.7
OS: Linux 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
CPU: 1xQEMU Virtual CPU version 2.5+ (2400Mhz, Xeon E5)
RAM: 512Mb
HARD: 7GB SSD

**Comment by wubenqi** [comment]
Add ram
