### ISSUE TITLE
测试服务的版本和master分支的代码是否相同

### ISSUE THREAD

**Issue by ChenMoGe2** [nebula-chat/chatengine#55]
按照补丁编译好的telegram，选择目前的测试服（47.103.102.219）可以登录并正常收发单聊消息的，但按照docker代码进行构建并使用客户端连接私服，客户端无法正常收发消息，且切换到别的应用程序再切回来后会一直显示Connecting...
服务端异常日志:
```
E0517 20:18:00.226402      85 rpc_recovery_handler.go:32] BizUnaryRecoveryHandler - goroutine 134 [running]:
runtime/debug.Stack(0x406234, 0xc0001d2a80, 0xc000b05300)
 /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/nebula-chat/chatengine/pkg/grpc_util.BizUnaryRecoveryHandler(0x18870e0, 0xc00084c870, 0x12e0a20, 0x2769c10, 0x46ec3e, 0xc000d7c0b0)
 /go/src/github.com/nebula-chat/chatengine/pkg/grpc_util/rpc_recovery_handler.go:32 +0x34
github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2.unaryRecoverFrom(0x18870e0, 0xc00084c870, 0x12e0a20, 0x2769c10, 0x1688358, 0xc000b053b0, 0x0)
 /go/src/github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2/interceptors.go:75 +0x5a
github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1.1(0x18870e0, 0xc00084c870, 0xc000c490a0, 0xc000b05ad8)
 /go/src/github.com/nebula-chat/chatengine/pkg/grpc_util/middleware/recovery2/interceptors.go:42 +0x77
panic(0x12e0a20, 0x2769c10)
 /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/nebula-chat/chatengine/messenger/biz_server/biz/core/message.(*MessageModel).SendMessage.func2(0xc000000006, 0xc0002955e0)
 /go/src/github.com/nebula-chat/chatengine/messenger/biz_server/biz/core/message/message_helper.go:559 +0x1d2
github.com/nebula-chat/chatengine/messenger/biz_server/biz/core/message.(*MessageModel).SendInternalMessage(0xc000913da0, 0x6, 0xc000ac02c0, 0x912b636b948557a7, 0xc0000d8900, 0xc00084cba0, 0xc000b05780, 0xbc, 0x203000)
 /go/src/github.com/nebula-chat/chatengine/messenger/biz_server/biz/core/message/message_helper.go:362 +0x698
github.com/nebula-chat/chatengine/messenger/biz_server/biz/core/message.(*MessageModel).SendMessage(0xc000913da0, 0xc000000006, 0xc000ac02c0, 0x912b636b948557a7, 0xc00084cba0, 0xc000b5c710, 0xc000cbadc0, 0xc000b5c720, 0x0, 0x0, ...)
 /go/src/github.com/nebula-chat/chatengine/messenger/biz_server/biz/core/message/message_helper.go:554 +0x110
github.com/nebula-chat/chatengine/messenger/biz_server/server/messages.(*MessagesSer
```

**Comment by wubenqi** [comment]
代码不一样的。

**Comment by wubenqi** [comment]
docker应该也能用的

**Comment by ChenMoGe2** [comment]
@wubenqi 好的谢谢，我这边用docker收发消息有问题登录没问题，我再研究研究
